<!-- ***** -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
 

  <script>
    const porm1 = new Promise((resolve, reject) => {
      setTimeout(() => {
        let arr = [1, 2, 3, 4, 5, 6];
        // resolve(arr); // Resolve with arr
        reject(arr);
      }, 4000);
    });
  
    porm1.then((arr) => {
      console.log(arr); // Accessing arr from the resolved result
    }).catch((error) => {
      console.error("Promise rejected:", error); // Handle promise rejection
    });
  </script>
  


    <!-- <script>

                let p=new Promise(function(accept,reject){
                              console.log("Order is pending");
                              setTimeout(function()
                              {
 
                                             console.log("I am promise , and i am fullfilled");
                                             accept(true);
                                           
                              },5000)
                })


                let p1=new Promise(function(accept,reject){
                              console.log("Order is pending");
                              setTimeout(function()
                              {
 
                                             console.log(" i am Rejected");
                                         
                                             reject(new Error("I am error"));
                              },5000)
                })


              //  console.log(p,p1);

              p.then((value)=>{
               console.log(value);

              })

      
              p1.catch((error)=>{
               console.log("some Error occur in code");

              })
               </script> -->
  </body>
</html>

<!-- ***** -->
